version: '3.5'

services:

  db:
    container_name: hotel-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - $HOME/.docker-volumes/hotel/postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: hotel-app
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
